version: '3.8'

services:
  # Development setup
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Client
      - "4000:4000"  # Server
    environment:
      - NODE_ENV=development
      - APP_PORT=4000
      - DB_PATH=/app/server/data/database.sqlite
      - JWT_SECRET=dev_jwt_secret_change_in_production
      - VITE_API_URL=http://localhost:4000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
      - /app/shared/node_modules
      - db_data:/app/server/data
    command: npm run dev
    stdin_open: true
    tty: true

volumes:
  db_data:
