version: '3.8'

services:
  # Production Client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client.prod
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:4000

  # Production Server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server.prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - APP_PORT=4000
      - DB_PATH=/app/data/database.sqlite
      - JWT_SECRET=${JWT_SECRET:-change_this_jwt_secret_in_production}
    volumes:
      - db_data:/app/data
    restart: unless-stopped

volumes:
  db_data:
